---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

This page is about making some plotly examples.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Let's look at NYC airbnb data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  ) %>% 
  drop_na(stars)
```

## Make a sactterplot

Here is a plotly scatterplot
```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price: $", price, "\nRating:", stars) #create a new variable with the format in brackets
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = .5
  )
```

## Plotly plot

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "viridis")
```

Here comes a bar chart

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```


## ggplotly

```{r}
# convert ggplot into ggplotly
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```









